### ISSUE TITLE
Build errors when using phonegap-plugin-barcodescanner

### ISSUE THREAD

**Issue by mttmllns** [adobe-marketing-cloud-mobile/aemmobile#51]
We get multiple Android build errors after adding the [phonegap barcode scanner plugin](https://github.com/phonegap/phonegap-plugin-barcodescanner).

Steps:
```
$ aemm project create barcodetest
$ cd barcodetest/
$ aemm platform add android
$ aemm plugin add phonegap-plugin-barcodescanner
$ aemm build android
```

Errors:
<pre>
ANDROID_HOME=/android
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.IllegalStateException: buildToolsVersion is not specified.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:600)
	at com.android.build.gradle.BasePlugin$10$1.call(BasePlugin.java:566)
	at com.android.build.gradle.BasePlugin$10$1.call(BasePlugin.java:563)
	at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:55)
	at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:47)
	at com.android.build.gradle.BasePlugin$10.execute(BasePlugin.java:562)
	at com.android.build.gradle.BasePlugin$10.execute(BasePlugin.java:559)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy11.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:510)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:90)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
	at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:125)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

FAILURE: Build failed with an exception.

<b>* Where:
Script '/Code/barcodebug/platforms/android/phonegap-plugin-barcodescanner/CordovaPlugins-barcodescanner.gradle' line: 3

* What went wrong:
A problem occurred evaluating script.
> Could not find property 'cdvMinSdkVersion' on root project 'android'.</b>

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.915 secs
Error: Error code 1 for command: /Code/barcodebug/platforms/android/gradlew with args: assembleDebug,-b,/Code/barcodebug/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true
</pre>

<pre>
ANDROID_HOME=/android
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:prepareAemmLibReleaseLibrary
:prepareBarcodescannerLibrary
:prepareComAdobeCreativesdkFoundationAuth09978Library
:prepareComAndroidSupportAnimatedVectorDrawable2321Library
:prepareComAndroidSupportAppcompatV72321Library
:prepareComAndroidSupportCardviewV72321Library
:prepareComAndroidSupportDesign2321Library
:prepareComAndroidSupportRecyclerviewV72321Library
:prepareComAndroidSupportSupportCompat2421Library
:prepareComAndroidSupportSupportCoreUi2421Library
:prepareComAndroidSupportSupportCoreUtils2421Library
:prepareComAndroidSupportSupportFragment2421Library
:prepareComAndroidSupportSupportMediaCompat2421Library
:prepareComAndroidSupportSupportV42421Library
:prepareComAndroidSupportSupportVectorDrawable2321Library
:prepareComGithubFengdaiAlertdialogproCore026Library
:prepareComGithubFengdaiAlertdialogproThemeMaterial026Library
:prepareComGoogleAndroidGmsPlayServicesBase840Library
:prepareComGoogleAndroidGmsPlayServicesBasement840Library
:prepareComGoogleAndroidGmsPlayServicesGcm840Library
:prepareComGoogleAndroidGmsPlayServicesMeasurement840Library
:prepareCordovaLibReleaseLibrary
:prepareUkCoChrisjenxCalligraphy220Library
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
<b>:processDebugManifest/Code/barcodebug/platforms/android/AndroidManifest.xml:31:9-36 Error:
	Attribute application@allowBackup value=(false) from [:aemm-lib-release:] AndroidManifest.xml:31:9-36
	is also present at [:barcodescanner:] AndroidManifest.xml:12:9-35 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:3:5-28:19 to override.
/Code/barcodebug/platforms/android/AndroidManifest.xml:33:9-48 Error:
	Attribute application@label value=(@string/homeScreenTitle) from [:aemm-lib-release:] AndroidManifest.xml:33:9-48
	is also present at [:barcodescanner:] AndroidManifest.xml:13:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:3:5-28:19 to override.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

:processDebugManifest FAILED
</b>
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 15.21 secs
Error: Error code 1 for command: /Code/barcodebug/platforms/android/gradlew with args: assembleDebug,-b,/Code/barcodebug/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true
</pre>

**Comment by adzellman** [comment]
@mttmllns @adobekirk It seems to me that this would require a change in aemm-android or phonegap-plugin-barcodescanner, not in the aemm cli.

**Comment by mttmllns** [comment]
The first error is an issue with the barcode plugin attempting to set an internal cordova variable.  We currently don't allow modifying these variables.  This can be worked around by commenting out the offending block in the plugin's gradle file:

**barcodebug/platforms/android/phonegap-plugin-barcodescanner/CordovaPlugins-barcodescanner.gradle:**
```gradle
// def minSdkVersion = 15

// if(cdvMinSdkVersion == null) {
//     ext.cdvMinSdkVersion = minSdkVersion;
// } else if (cdvMinSdkVersion.toInteger() < minSdkVersion) {
//     ext.cdvMinSdkVersion = minSdkVersion;
// }

repositories{
    jcenter()
    flatDir{
        dirs 'libs'
    }
}
...
```

The second error indicates a conflict when merging the two AndroidManifest.xml files in the aemm library AAR and the barcodescanner library AAR.  The only way to fix this is by letting the manifest merger know how it should resolve the conflict.  You can do this by adding the tools namespace and using the markers suggested in the error message.  Modifications bolded:

**barcodebug/platforms/android/AndroidManifest.xml:**
<pre>
&lt;?xml version='1.0' encoding='utf-8'?&gt;
&lt;manifest
    package="com.adobe.dps.CordovaPlugins" 
    xmlns:aemm="http://ns.adobe.com/aemm" 
    xmlns:android="http://schemas.android.com/apk/res/android" 
    <b>xmlns:tools="http://schemas.android.com/tools"</b>&gt;
    &lt;application
        android:name="com.adobe.dps.viewer.MainApplication"
        <b>android:allowBackup="false"
        android:label="@string/homeScreenTitle"
        tools:replace="android:allowBackup, android:label"</b>&gt;
        &lt;activity android:name="com.adobe.dps.viewer.collectionview.CollectionActivity"&gt;
...
</pre>

More info on the manifest merger: http://g.co/androidstudio/manifest-merger
